WHENEVER OSERROR EXIT FAILURE ROLLBACK
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

SET SQLBLANKLINES ON
SET DEFINE OFF
SET SERVEROUTPUT ON

PROMPT ============================================================
PROMPT SuperMarket SIG - Esquema inicial Oracle
PROMPT Migracion: 001
PROMPT Contrato ERP: 1.0
PROMPT ============================================================

CREATE TABLE sig_sincronizacion (
    id                         NUMBER(19)
                               GENERATED BY DEFAULT ON NULL AS IDENTITY,

    version_contrato           VARCHAR2(20 CHAR) NOT NULL,
    fuente                     VARCHAR2(100 CHAR) NOT NULL,
    modo                       VARCHAR2(20 CHAR) NOT NULL,
    estado                     VARCHAR2(20 CHAR) NOT NULL,

    fecha_generacion           TIMESTAMP WITH TIME ZONE NOT NULL,
    fecha_inicio               TIMESTAMP WITH TIME ZONE
                               DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_fin                  TIMESTAMP WITH TIME ZONE,

    total_categorias           NUMBER(10) DEFAULT 0 NOT NULL,
    total_empresas             NUMBER(10) DEFAULT 0 NOT NULL,
    total_proveedores          NUMBER(10) DEFAULT 0 NOT NULL,
    total_productos            NUMBER(10) DEFAULT 0 NOT NULL,
    total_clientes             NUMBER(10) DEFAULT 0 NOT NULL,
    total_ventas               NUMBER(10) DEFAULT 0 NOT NULL,
    total_detalles_venta       NUMBER(10) DEFAULT 0 NOT NULL,
    total_pedidos              NUMBER(10) DEFAULT 0 NOT NULL,
    total_entregas             NUMBER(10) DEFAULT 0 NOT NULL,
    total_lotes                NUMBER(10) DEFAULT 0 NOT NULL,
    total_movimientos          NUMBER(10) DEFAULT 0 NOT NULL,

    mensaje                    VARCHAR2(2000 CHAR),

    CONSTRAINT pk_sig_sync
        PRIMARY KEY (id),

    CONSTRAINT ck_sig_sync_modo
        CHECK (modo IN ('completa', 'incremental')),

    CONSTRAINT ck_sig_sync_estado
        CHECK (estado IN ('iniciada', 'completada', 'fallida')),

    CONSTRAINT ck_sig_sync_totales
        CHECK (
            total_categorias >= 0
            AND total_empresas >= 0
            AND total_proveedores >= 0
            AND total_productos >= 0
            AND total_clientes >= 0
            AND total_ventas >= 0
            AND total_detalles_venta >= 0
            AND total_pedidos >= 0
            AND total_entregas >= 0
            AND total_lotes >= 0
            AND total_movimientos >= 0
        )
);

CREATE TABLE sig_categoria (
    id                         NUMBER(19)
                               GENERATED BY DEFAULT ON NULL AS IDENTITY,

    id_origen                  NUMBER(19) NOT NULL,
    nombre                     VARCHAR2(200 CHAR) NOT NULL,
    descripcion                VARCHAR2(1000 CHAR),

    activo_sync                NUMBER(1) DEFAULT 1 NOT NULL,
    id_sync_ultima             NUMBER(19) NOT NULL,
    sincronizado_en            TIMESTAMP WITH TIME ZONE
                               DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_sig_categoria
        PRIMARY KEY (id),

    CONSTRAINT uk_sig_categoria_origen
        UNIQUE (id_origen),

    CONSTRAINT fk_sig_categoria_sync
        FOREIGN KEY (id_sync_ultima)
        REFERENCES sig_sincronizacion (id),

    CONSTRAINT ck_sig_categoria_origen
        CHECK (id_origen > 0),

    CONSTRAINT ck_sig_categoria_activo
        CHECK (activo_sync IN (0, 1))
);

CREATE TABLE sig_empresa (
    id                         NUMBER(19)
                               GENERATED BY DEFAULT ON NULL AS IDENTITY,

    id_origen                  NUMBER(19) NOT NULL,
    nombre                     VARCHAR2(200 CHAR) NOT NULL,
    responsable                VARCHAR2(200 CHAR),
    telefono                   VARCHAR2(50 CHAR),
    correo                     VARCHAR2(320 CHAR),
    estado                     VARCHAR2(40 CHAR) NOT NULL,

    activo_sync                NUMBER(1) DEFAULT 1 NOT NULL,
    id_sync_ultima             NUMBER(19) NOT NULL,
    sincronizado_en            TIMESTAMP WITH TIME ZONE
                               DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_sig_empresa
        PRIMARY KEY (id),

    CONSTRAINT uk_sig_empresa_origen
        UNIQUE (id_origen),

    CONSTRAINT fk_sig_empresa_sync
        FOREIGN KEY (id_sync_ultima)
        REFERENCES sig_sincronizacion (id),

    CONSTRAINT ck_sig_empresa_origen
        CHECK (id_origen > 0),

    CONSTRAINT ck_sig_empresa_activo
        CHECK (activo_sync IN (0, 1))
);

CREATE TABLE sig_proveedor (
    id                         NUMBER(19)
                               GENERATED BY DEFAULT ON NULL AS IDENTITY,

    id_origen                  NUMBER(19) NOT NULL,
    empresa_id_origen          NUMBER(19) NOT NULL,
    identificacion             VARCHAR2(50 CHAR),
    nombre                     VARCHAR2(250 CHAR) NOT NULL,
    telefono                   VARCHAR2(50 CHAR),
    correo                     VARCHAR2(320 CHAR),
    estado                     VARCHAR2(40 CHAR) NOT NULL,

    activo_sync                NUMBER(1) DEFAULT 1 NOT NULL,
    id_sync_ultima             NUMBER(19) NOT NULL,
    sincronizado_en            TIMESTAMP WITH TIME ZONE
                               DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_sig_proveedor
        PRIMARY KEY (id),

    CONSTRAINT uk_sig_proveedor_origen
        UNIQUE (id_origen),

    CONSTRAINT fk_sig_proveedor_empresa
        FOREIGN KEY (empresa_id_origen)
        REFERENCES sig_empresa (id_origen),

    CONSTRAINT fk_sig_proveedor_sync
        FOREIGN KEY (id_sync_ultima)
        REFERENCES sig_sincronizacion (id),

    CONSTRAINT ck_sig_proveedor_origen
        CHECK (id_origen > 0),

    CONSTRAINT ck_sig_proveedor_activo
        CHECK (activo_sync IN (0, 1))
);

CREATE TABLE sig_producto (
    id                         NUMBER(19)
                               GENERATED BY DEFAULT ON NULL AS IDENTITY,

    id_origen                  NUMBER(19) NOT NULL,
    categoria_id_origen        NUMBER(19) NOT NULL,
    codigo_barra               VARCHAR2(100 CHAR),
    nombre                     VARCHAR2(250 CHAR) NOT NULL,

    stock_actual               NUMBER(19) NOT NULL,
    stock_minimo               NUMBER(19) NOT NULL,
    precio_venta               NUMBER(14, 2) NOT NULL,
    estado                     VARCHAR2(40 CHAR) NOT NULL,

    activo_sync                NUMBER(1) DEFAULT 1 NOT NULL,
    id_sync_ultima             NUMBER(19) NOT NULL,
    sincronizado_en            TIMESTAMP WITH TIME ZONE
                               DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_sig_producto
        PRIMARY KEY (id),

    CONSTRAINT uk_sig_producto_origen
        UNIQUE (id_origen),

    CONSTRAINT fk_sig_producto_categoria
        FOREIGN KEY (categoria_id_origen)
        REFERENCES sig_categoria (id_origen),

    CONSTRAINT fk_sig_producto_sync
        FOREIGN KEY (id_sync_ultima)
        REFERENCES sig_sincronizacion (id),

    CONSTRAINT ck_sig_producto_origen
        CHECK (id_origen > 0),

    CONSTRAINT ck_sig_producto_stock
        CHECK (
            stock_actual >= 0
            AND stock_minimo >= 0
        ),

    CONSTRAINT ck_sig_producto_precio
        CHECK (precio_venta >= 0),

    CONSTRAINT ck_sig_producto_activo
        CHECK (activo_sync IN (0, 1))
);

CREATE TABLE sig_cliente (
    id                         NUMBER(19)
                               GENERATED BY DEFAULT ON NULL AS IDENTITY,

    id_origen                  NUMBER(19) NOT NULL,
    identificacion             VARCHAR2(50 CHAR),
    nombre                     VARCHAR2(250 CHAR) NOT NULL,
    correo                     VARCHAR2(320 CHAR),
    telefono                   VARCHAR2(50 CHAR),

    activo_sync                NUMBER(1) DEFAULT 1 NOT NULL,
    id_sync_ultima             NUMBER(19) NOT NULL,
    sincronizado_en            TIMESTAMP WITH TIME ZONE
                               DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_sig_cliente
        PRIMARY KEY (id),

    CONSTRAINT uk_sig_cliente_origen
        UNIQUE (id_origen),

    CONSTRAINT fk_sig_cliente_sync
        FOREIGN KEY (id_sync_ultima)
        REFERENCES sig_sincronizacion (id),

    CONSTRAINT ck_sig_cliente_origen
        CHECK (id_origen >= 0),

    CONSTRAINT ck_sig_cliente_activo
        CHECK (activo_sync IN (0, 1))
);

CREATE TABLE sig_venta (
    id                         NUMBER(19)
                               GENERATED BY DEFAULT ON NULL AS IDENTITY,

    id_origen                  NUMBER(19) NOT NULL,
    cliente_id_origen          NUMBER(19),
    numero_factura             VARCHAR2(100 CHAR) NOT NULL,

    fecha_venta                TIMESTAMP WITH TIME ZONE NOT NULL,
    canal                      VARCHAR2(20 CHAR) NOT NULL,
    estado                     VARCHAR2(40 CHAR) NOT NULL,

    subtotal                   NUMBER(14, 2) NOT NULL,
    descuento                  NUMBER(14, 2) NOT NULL,
    iva                        NUMBER(14, 2) NOT NULL,
    total                      NUMBER(14, 2) NOT NULL,

    activo_sync                NUMBER(1) DEFAULT 1 NOT NULL,
    id_sync_ultima             NUMBER(19) NOT NULL,
    sincronizado_en            TIMESTAMP WITH TIME ZONE
                               DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_sig_venta
        PRIMARY KEY (id),

    CONSTRAINT uk_sig_venta_origen
        UNIQUE (id_origen),

    CONSTRAINT fk_sig_venta_cliente
        FOREIGN KEY (cliente_id_origen)
        REFERENCES sig_cliente (id_origen),

    CONSTRAINT fk_sig_venta_sync
        FOREIGN KEY (id_sync_ultima)
        REFERENCES sig_sincronizacion (id),

    CONSTRAINT ck_sig_venta_origen
        CHECK (id_origen > 0),

    CONSTRAINT ck_sig_venta_canal
        CHECK (canal IN ('pos', 'movil')),

    CONSTRAINT ck_sig_venta_valores
        CHECK (
            subtotal >= 0
            AND descuento >= 0
            AND iva >= 0
            AND total >= 0
        ),

    CONSTRAINT ck_sig_venta_activo
        CHECK (activo_sync IN (0, 1))
);

CREATE TABLE sig_detalle_venta (
    id                         NUMBER(19)
                               GENERATED BY DEFAULT ON NULL AS IDENTITY,

    id_origen                  NUMBER(19) NOT NULL,
    venta_id_origen            NUMBER(19) NOT NULL,
    producto_id_origen         NUMBER(19) NOT NULL,

    cantidad                   NUMBER(19) NOT NULL,
    precio_unitario            NUMBER(14, 2) NOT NULL,
    subtotal                   NUMBER(14, 2) NOT NULL,
    descuento                  NUMBER(14, 2) NOT NULL,
    iva                        NUMBER(14, 2) NOT NULL,
    total                      NUMBER(14, 2) NOT NULL,

    activo_sync                NUMBER(1) DEFAULT 1 NOT NULL,
    id_sync_ultima             NUMBER(19) NOT NULL,
    sincronizado_en            TIMESTAMP WITH TIME ZONE
                               DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_sig_detalle_venta
        PRIMARY KEY (id),

    CONSTRAINT uk_sig_detalle_venta_origen
        UNIQUE (id_origen),

    CONSTRAINT fk_sig_dventa_venta
        FOREIGN KEY (venta_id_origen)
        REFERENCES sig_venta (id_origen),

    CONSTRAINT fk_sig_dventa_producto
        FOREIGN KEY (producto_id_origen)
        REFERENCES sig_producto (id_origen),

    CONSTRAINT fk_sig_dventa_sync
        FOREIGN KEY (id_sync_ultima)
        REFERENCES sig_sincronizacion (id),

    CONSTRAINT ck_sig_dventa_origen
        CHECK (id_origen > 0),

    CONSTRAINT ck_sig_dventa_cantidad
        CHECK (cantidad > 0),

    CONSTRAINT ck_sig_dventa_valores
        CHECK (
            precio_unitario >= 0
            AND subtotal >= 0
            AND descuento >= 0
            AND iva >= 0
            AND total >= 0
        ),

    CONSTRAINT ck_sig_dventa_activo
        CHECK (activo_sync IN (0, 1))
);

CREATE TABLE sig_pedido (
    id                         NUMBER(19)
                               GENERATED BY DEFAULT ON NULL AS IDENTITY,

    id_origen                  NUMBER(19) NOT NULL,
    empresa_id_origen          NUMBER(19) NOT NULL,

    motivo                     VARCHAR2(1000 CHAR) NOT NULL,
    estado                     VARCHAR2(40 CHAR) NOT NULL,

    fecha_pedido               TIMESTAMP WITH TIME ZONE NOT NULL,
    fecha_esperada             TIMESTAMP WITH TIME ZONE,

    cantidad_solicitada        NUMBER(19) NOT NULL,
    cantidad_recibida          NUMBER(19) NOT NULL,
    total                      NUMBER(14, 2) NOT NULL,

    activo_sync                NUMBER(1) DEFAULT 1 NOT NULL,
    id_sync_ultima             NUMBER(19) NOT NULL,
    sincronizado_en            TIMESTAMP WITH TIME ZONE
                               DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_sig_pedido
        PRIMARY KEY (id),

    CONSTRAINT uk_sig_pedido_origen
        UNIQUE (id_origen),

    CONSTRAINT fk_sig_pedido_empresa
        FOREIGN KEY (empresa_id_origen)
        REFERENCES sig_empresa (id_origen),

    CONSTRAINT fk_sig_pedido_sync
        FOREIGN KEY (id_sync_ultima)
        REFERENCES sig_sincronizacion (id),

    CONSTRAINT ck_sig_pedido_origen
        CHECK (id_origen > 0),

    CONSTRAINT ck_sig_pedido_cantidades
        CHECK (
            cantidad_solicitada >= 0
            AND cantidad_recibida >= 0
        ),

    CONSTRAINT ck_sig_pedido_total
        CHECK (total >= 0),

    CONSTRAINT ck_sig_pedido_activo
        CHECK (activo_sync IN (0, 1))
);

CREATE TABLE sig_entrega (
    id                         NUMBER(19)
                               GENERATED BY DEFAULT ON NULL AS IDENTITY,

    id_origen                  NUMBER(19) NOT NULL,
    pedido_id_origen           NUMBER(19) NOT NULL,
    proveedor_id_origen        NUMBER(19) NOT NULL,

    fecha_entrega              TIMESTAMP WITH TIME ZONE,
    estado                     VARCHAR2(40 CHAR) NOT NULL,
    cantidad_recibida          NUMBER(19) NOT NULL,

    activo_sync                NUMBER(1) DEFAULT 1 NOT NULL,
    id_sync_ultima             NUMBER(19) NOT NULL,
    sincronizado_en            TIMESTAMP WITH TIME ZONE
                               DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_sig_entrega
        PRIMARY KEY (id),

    CONSTRAINT uk_sig_entrega_origen
        UNIQUE (id_origen),

    CONSTRAINT fk_sig_entrega_pedido
        FOREIGN KEY (pedido_id_origen)
        REFERENCES sig_pedido (id_origen),

    CONSTRAINT fk_sig_entrega_proveedor
        FOREIGN KEY (proveedor_id_origen)
        REFERENCES sig_proveedor (id_origen),

    CONSTRAINT fk_sig_entrega_sync
        FOREIGN KEY (id_sync_ultima)
        REFERENCES sig_sincronizacion (id),

    CONSTRAINT ck_sig_entrega_origen
        CHECK (id_origen > 0),

    CONSTRAINT ck_sig_entrega_cantidad
        CHECK (cantidad_recibida >= 0),

    CONSTRAINT ck_sig_entrega_activo
        CHECK (activo_sync IN (0, 1))
);

CREATE TABLE sig_lote (
    id                         NUMBER(19)
                               GENERATED BY DEFAULT ON NULL AS IDENTITY,

    id_origen                  NUMBER(19) NOT NULL,
    producto_id_origen         NUMBER(19) NOT NULL,

    fecha_caducidad            DATE NOT NULL,
    stock                      NUMBER(19) NOT NULL,
    estado                     VARCHAR2(40 CHAR) NOT NULL,

    activo_sync                NUMBER(1) DEFAULT 1 NOT NULL,
    id_sync_ultima             NUMBER(19) NOT NULL,
    sincronizado_en            TIMESTAMP WITH TIME ZONE
                               DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_sig_lote
        PRIMARY KEY (id),

    CONSTRAINT uk_sig_lote_origen
        UNIQUE (id_origen),

    CONSTRAINT fk_sig_lote_producto
        FOREIGN KEY (producto_id_origen)
        REFERENCES sig_producto (id_origen),

    CONSTRAINT fk_sig_lote_sync
        FOREIGN KEY (id_sync_ultima)
        REFERENCES sig_sincronizacion (id),

    CONSTRAINT ck_sig_lote_origen
        CHECK (id_origen > 0),

    CONSTRAINT ck_sig_lote_stock
        CHECK (stock >= 0),

    CONSTRAINT ck_sig_lote_activo
        CHECK (activo_sync IN (0, 1))
);

CREATE TABLE sig_movimiento_inv (
    id                         NUMBER(19)
                               GENERATED BY DEFAULT ON NULL AS IDENTITY,

    id_origen                  NUMBER(19) NOT NULL,
    producto_id_origen         NUMBER(19) NOT NULL,
    lote_id_origen             NUMBER(19),

    tipo                       VARCHAR2(60 CHAR) NOT NULL,
    cantidad                   NUMBER(19) NOT NULL,

    stock_producto_anterior    NUMBER(19),
    stock_producto_posterior   NUMBER(19),
    stock_lote_anterior        NUMBER(19),
    stock_lote_posterior       NUMBER(19),

    documento_origen           VARCHAR2(200 CHAR),
    usuario_origen             VARCHAR2(150 CHAR),
    fecha_movimiento           TIMESTAMP WITH TIME ZONE NOT NULL,

    activo_sync                NUMBER(1) DEFAULT 1 NOT NULL,
    id_sync_ultima             NUMBER(19) NOT NULL,
    sincronizado_en            TIMESTAMP WITH TIME ZONE
                               DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_sig_movimiento
        PRIMARY KEY (id),

    CONSTRAINT uk_sig_movimiento_origen
        UNIQUE (id_origen),

    CONSTRAINT fk_sig_movimiento_producto
        FOREIGN KEY (producto_id_origen)
        REFERENCES sig_producto (id_origen),

    CONSTRAINT fk_sig_movimiento_lote
        FOREIGN KEY (lote_id_origen)
        REFERENCES sig_lote (id_origen),

    CONSTRAINT fk_sig_movimiento_sync
        FOREIGN KEY (id_sync_ultima)
        REFERENCES sig_sincronizacion (id),

    CONSTRAINT ck_sig_movimiento_origen
        CHECK (id_origen > 0),

    CONSTRAINT ck_sig_movimiento_cantidad
        CHECK (cantidad <> 0),

    CONSTRAINT ck_sig_movimiento_activo
        CHECK (activo_sync IN (0, 1))
);

CREATE TABLE sig_dispositivo_iot (
    id                         NUMBER(19)
                               GENERATED BY DEFAULT ON NULL AS IDENTITY,

    codigo                     VARCHAR2(100 CHAR) NOT NULL,
    nombre                     VARCHAR2(200 CHAR) NOT NULL,
    ubicacion                  VARCHAR2(300 CHAR),
    tipo_sensor                VARCHAR2(100 CHAR),

    temperatura_minima         NUMBER(8, 2) NOT NULL,
    temperatura_maxima         NUMBER(8, 2) NOT NULL,

    activo                     NUMBER(1) DEFAULT 1 NOT NULL,
    creado_en                  TIMESTAMP WITH TIME ZONE
                               DEFAULT CURRENT_TIMESTAMP NOT NULL,
    actualizado_en             TIMESTAMP WITH TIME ZONE
                               DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_sig_dispositivo
        PRIMARY KEY (id),

    CONSTRAINT uk_sig_dispositivo_codigo
        UNIQUE (codigo),

    CONSTRAINT ck_sig_dispositivo_rango
        CHECK (
            temperatura_minima < temperatura_maxima
        ),

    CONSTRAINT ck_sig_dispositivo_activo
        CHECK (activo IN (0, 1))
);

CREATE TABLE sig_lectura_iot (
    id                         NUMBER(19)
                               GENERATED BY DEFAULT ON NULL AS IDENTITY,

    codigo_dispositivo         VARCHAR2(100 CHAR) NOT NULL,
    temperatura                NUMBER(8, 2) NOT NULL,
    humedad                    NUMBER(8, 2),
    estado                     VARCHAR2(30 CHAR) NOT NULL,

    fecha_lectura              TIMESTAMP WITH TIME ZONE NOT NULL,
    fecha_registro             TIMESTAMP WITH TIME ZONE
                               DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_sig_lectura
        PRIMARY KEY (id),

    CONSTRAINT fk_sig_lectura_dispositivo
        FOREIGN KEY (codigo_dispositivo)
        REFERENCES sig_dispositivo_iot (codigo),

    CONSTRAINT ck_sig_lectura_humedad
        CHECK (
            humedad IS NULL
            OR humedad BETWEEN 0 AND 100
        ),

    CONSTRAINT ck_sig_lectura_estado
        CHECK (estado IN ('normal', 'fuera_rango'))
);

CREATE TABLE sig_alerta (
    id                         NUMBER(19)
                               GENERATED BY DEFAULT ON NULL AS IDENTITY,

    id_lectura                 NUMBER(19) NOT NULL,

    tipo                       VARCHAR2(100 CHAR) NOT NULL,
    severidad                  VARCHAR2(30 CHAR) NOT NULL,
    mensaje                    VARCHAR2(2000 CHAR) NOT NULL,
    estado                     VARCHAR2(30 CHAR) NOT NULL,

    fecha_apertura             TIMESTAMP WITH TIME ZONE
                               DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_reconocimiento       TIMESTAMP WITH TIME ZONE,
    fecha_cierre               TIMESTAMP WITH TIME ZONE,

    CONSTRAINT pk_sig_alerta
        PRIMARY KEY (id),

    CONSTRAINT uk_sig_alerta_lectura
        UNIQUE (id_lectura),

    CONSTRAINT fk_sig_alerta_lectura
        FOREIGN KEY (id_lectura)
        REFERENCES sig_lectura_iot (id),

    CONSTRAINT ck_sig_alerta_severidad
        CHECK (
            severidad IN ('baja', 'media', 'alta', 'critica')
        ),

    CONSTRAINT ck_sig_alerta_estado
        CHECK (
            estado IN ('abierta', 'reconocida', 'cerrada')
        )
);

CREATE TABLE sig_incidente (
    id                         NUMBER(19)
                               GENERATED BY DEFAULT ON NULL AS IDENTITY,

    id_alerta                  NUMBER(19) NOT NULL,

    codigo                     VARCHAR2(100 CHAR) NOT NULL,
    titulo                     VARCHAR2(300 CHAR) NOT NULL,
    descripcion                VARCHAR2(2000 CHAR) NOT NULL,
    severidad                  VARCHAR2(30 CHAR) NOT NULL,
    estado                     VARCHAR2(30 CHAR) NOT NULL,
    responsable                VARCHAR2(200 CHAR),

    fecha_apertura             TIMESTAMP WITH TIME ZONE
                               DEFAULT CURRENT_TIMESTAMP NOT NULL,
    fecha_reconocimiento       TIMESTAMP WITH TIME ZONE,
    fecha_resolucion           TIMESTAMP WITH TIME ZONE,
    fecha_cierre               TIMESTAMP WITH TIME ZONE,

    CONSTRAINT pk_sig_incidente
        PRIMARY KEY (id),

    CONSTRAINT uk_sig_incidente_alerta
        UNIQUE (id_alerta),

    CONSTRAINT uk_sig_incidente_codigo
        UNIQUE (codigo),

    CONSTRAINT fk_sig_incidente_alerta
        FOREIGN KEY (id_alerta)
        REFERENCES sig_alerta (id),

    CONSTRAINT ck_sig_incidente_severidad
        CHECK (
            severidad IN ('baja', 'media', 'alta', 'critica')
        ),

    CONSTRAINT ck_sig_incidente_estado
        CHECK (
            estado IN (
                'abierto',
                'reconocido',
                'en_tratamiento',
                'resuelto',
                'cerrado'
            )
        )
);

CREATE TABLE sig_accion_correctiva (
    id                         NUMBER(19)
                               GENERATED BY DEFAULT ON NULL AS IDENTITY,

    id_incidente               NUMBER(19) NOT NULL,
    descripcion                VARCHAR2(2000 CHAR) NOT NULL,
    responsable                VARCHAR2(200 CHAR) NOT NULL,
    resultado                  VARCHAR2(2000 CHAR),

    fecha_accion               TIMESTAMP WITH TIME ZONE
                               DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_sig_accion
        PRIMARY KEY (id),

    CONSTRAINT fk_sig_accion_incidente
        FOREIGN KEY (id_incidente)
        REFERENCES sig_incidente (id)
);

CREATE TABLE sig_auditoria (
    id                         NUMBER(19)
                               GENERATED BY DEFAULT ON NULL AS IDENTITY,

    actor                      VARCHAR2(200 CHAR) NOT NULL,
    accion                     VARCHAR2(150 CHAR) NOT NULL,
    modulo                     VARCHAR2(100 CHAR) NOT NULL,
    entidad                    VARCHAR2(100 CHAR) NOT NULL,
    id_registro                VARCHAR2(100 CHAR) NOT NULL,
    resultado                  VARCHAR2(50 CHAR) NOT NULL,
    detalle                    VARCHAR2(2000 CHAR),

    fecha_evento               TIMESTAMP WITH TIME ZONE
                               DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT pk_sig_auditoria
        PRIMARY KEY (id)
);

CREATE INDEX idx_sig_sync_fecha
    ON sig_sincronizacion (fecha_inicio);

CREATE INDEX idx_sig_sync_estado
    ON sig_sincronizacion (estado);

CREATE INDEX idx_sig_prov_empresa
    ON sig_proveedor (empresa_id_origen);

CREATE INDEX idx_sig_prod_categoria
    ON sig_producto (categoria_id_origen);

CREATE INDEX idx_sig_prod_estado
    ON sig_producto (estado, activo_sync);

CREATE INDEX idx_sig_venta_cliente
    ON sig_venta (cliente_id_origen);

CREATE INDEX idx_sig_venta_fecha
    ON sig_venta (fecha_venta);

CREATE INDEX idx_sig_venta_estado
    ON sig_venta (estado, activo_sync);

CREATE INDEX idx_sig_dventa_venta
    ON sig_detalle_venta (venta_id_origen);

CREATE INDEX idx_sig_dventa_producto
    ON sig_detalle_venta (producto_id_origen);

CREATE INDEX idx_sig_pedido_empresa
    ON sig_pedido (empresa_id_origen);

CREATE INDEX idx_sig_pedido_fecha
    ON sig_pedido (fecha_pedido);

CREATE INDEX idx_sig_pedido_estado
    ON sig_pedido (estado, activo_sync);

CREATE INDEX idx_sig_entrega_pedido
    ON sig_entrega (pedido_id_origen);

CREATE INDEX idx_sig_entrega_proveedor
    ON sig_entrega (proveedor_id_origen);

CREATE INDEX idx_sig_lote_producto
    ON sig_lote (producto_id_origen);

CREATE INDEX idx_sig_lote_caducidad
    ON sig_lote (fecha_caducidad);

CREATE INDEX idx_sig_mov_producto
    ON sig_movimiento_inv (producto_id_origen);

CREATE INDEX idx_sig_mov_lote
    ON sig_movimiento_inv (lote_id_origen);

CREATE INDEX idx_sig_mov_fecha
    ON sig_movimiento_inv (fecha_movimiento);

CREATE INDEX idx_sig_lectura_disp_fecha
    ON sig_lectura_iot (
        codigo_dispositivo,
        fecha_lectura
    );

CREATE INDEX idx_sig_alerta_estado
    ON sig_alerta (estado, fecha_apertura);

CREATE INDEX idx_sig_incidente_estado
    ON sig_incidente (estado, fecha_apertura);

CREATE INDEX idx_sig_accion_incidente
    ON sig_accion_correctiva (
        id_incidente,
        fecha_accion
    );

CREATE INDEX idx_sig_auditoria_fecha
    ON sig_auditoria (fecha_evento);

CREATE INDEX idx_sig_auditoria_accion
    ON sig_auditoria (accion);

COMMENT ON TABLE sig_sincronizacion IS
    'Historial de sincronizaciones entre el ERP PostgreSQL y el SIG Oracle.';

COMMENT ON TABLE sig_categoria IS
    'Categorías empresariales sincronizadas desde el ERP.';

COMMENT ON TABLE sig_empresa IS
    'Empresas proveedoras sincronizadas desde el ERP.';

COMMENT ON TABLE sig_proveedor IS
    'Proveedores sincronizados desde el ERP.';

COMMENT ON TABLE sig_producto IS
    'Productos utilizados por los indicadores gerenciales.';

COMMENT ON TABLE sig_cliente IS
    'Clientes sincronizados; el identificador de origen cero representa consumidor final.';

COMMENT ON TABLE sig_venta IS
    'Cabeceras de ventas sincronizadas para análisis gerencial.';

COMMENT ON TABLE sig_detalle_venta IS
    'Detalles de productos vendidos.';

COMMENT ON TABLE sig_pedido IS
    'Pedidos utilizados para indicadores de abastecimiento.';

COMMENT ON TABLE sig_entrega IS
    'Entregas confirmadas sincronizadas desde el ERP.';

COMMENT ON TABLE sig_lote IS
    'Lotes utilizados para análisis de caducidad e inventario.';

COMMENT ON TABLE sig_movimiento_inv IS
    'Movimientos de inventario sincronizados desde el ERP.';

COMMENT ON TABLE sig_dispositivo_iot IS
    'Dispositivos IoT registrados en el SIG.';

COMMENT ON TABLE sig_lectura_iot IS
    'Lecturas de temperatura y humedad de cadena de frío.';

COMMENT ON TABLE sig_alerta IS
    'Alertas generadas automáticamente por lecturas fuera de rango.';

COMMENT ON TABLE sig_incidente IS
    'Incidentes de calidad administrados mediante el proceso BPM.';

COMMENT ON TABLE sig_accion_correctiva IS
    'Acciones correctivas aplicadas a incidentes de calidad.';

COMMENT ON TABLE sig_auditoria IS
    'Trazabilidad de acciones operativas y automáticas del SIG.';

COMMIT;

PROMPT ============================================================
PROMPT Migracion 001 creada correctamente
PROMPT Tablas esperadas: 18
PROMPT ============================================================